/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/app/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/app/components/AppHeader.vue')['default']
    MainAdvantages: typeof import('./src/modules/main/components/MainAdvantages.vue')['default']
    MainHero: typeof import('./src/modules/main/components/MainHero.vue')['default']
    MainPromo: typeof import('./src/modules/main/components/MainPromo.vue')['default']
    MainSlider: typeof import('./src/modules/main/components/MainSlider.vue')['default']
    MainView: typeof import('./src/modules/main/views/MainView.vue')['default']
    MainWidget: typeof import('./src/modules/main/widgets/MainWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
